name: Auto Git

on:
  workflow_dispatch:

jobs:
  update_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Check if main branch exists
        id: check_branch
        run: |
          sudo apt-get install -y jq
          BRANCH_EXISTS=$(git ls-remote --heads origin main | wc -l)
          echo "::set-output name=branch_exists::$BRANCH_EXISTS"

      - name: Create main branch if not exists
        if: steps.check_branch.outputs.branch_exists == '0'
        run: |
          git checkout -b main
          git push -u origin main

      - name: Switch back to dev branch
        run: |
          git checkout dev

      - name: Update logs.txt
        run: |
          if [ ! -f logs.txt ]; then
            touch logs.txt
          fi
          echo "$(TZ=":Asia/Karachi" date "+%I:%M:%S %p - %d-%b-%y")" > logs.txt

      - name: Commit and push
        run: |
          git config --local user.email "shafqatjan86@gmail.com"
          git config --local user.name "Shafqat Jan"
          git add logs.txt
          git commit -m "$(TZ=":Asia/Karachi" date "+%d-%b-%y-%I:%M:%S:%p")"
          git push
      
      - name: Create Pull Request
        run: |
          RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GIT_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{
            "title":"Update logs.txt",
            "body":"Update logs.txt",
            "head":"dev",
            "base":"main"
          }')

          # Extract the pull request number from the response
          PR_NUMBER=$(echo "$RESPONSE" | jq '.number')

          # Assign the reviewer to the pull request
          curl -X POST -H "Authorization: token ${{ secrets.GIT_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers \
          -d '{
            "reviewers": ["shafqatjan86@gmail.com"]
          }'

      - name: Merge Pull Request
        run: |
          PR_NUMBER=$(curl -H "Authorization: token ${{ secrets.GIT_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:dev \
          | jq '.[0].number')
          
          curl -X PUT -H "Authorization: token ${{ secrets.GIT_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge
